// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0-zF2ktCAPUdOrZAT-mlQL_IXDdPmhaA',
    appId: '1:23560088534:web:11c675f803d082e6bd5277',
    messagingSenderId: '23560088534',
    projectId: 'chitchat-39461',
    authDomain: 'chitchat-39461.firebaseapp.com',
    storageBucket: 'chitchat-39461.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBTW-ZMqw6edRcTdzHIeavNEcFH754u0w',
    appId: '1:23560088534:android:80965053e1072ab4bd5277',
    messagingSenderId: '23560088534',
    projectId: 'chitchat-39461',
    storageBucket: 'chitchat-39461.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCxPkcopXN4IZdO7OTp91lo4MPWwEDZ7rw',
    appId: '1:23560088534:ios:b4f9199480e80503bd5277',
    messagingSenderId: '23560088534',
    projectId: 'chitchat-39461',
    storageBucket: 'chitchat-39461.appspot.com',
    androidClientId: '23560088534-meii3mu943odd08ej3pc5jh0l0pg05lu.apps.googleusercontent.com',
    iosClientId: '23560088534-vkm1u6au1tls4kvc07jjiglq9ge9q15d.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCxPkcopXN4IZdO7OTp91lo4MPWwEDZ7rw',
    appId: '1:23560088534:ios:d5e5ed3f8434c527bd5277',
    messagingSenderId: '23560088534',
    projectId: 'chitchat-39461',
    storageBucket: 'chitchat-39461.appspot.com',
    androidClientId: '23560088534-meii3mu943odd08ej3pc5jh0l0pg05lu.apps.googleusercontent.com',
    iosClientId: '23560088534-sptp46idev03ibqe0em4l91a4jg8halh.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
